application: python-starter
version: 2
runtime: python27
api_version: 1
threadsafe: true


instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  max_concurrent_requests: 8


handlers:
- url: /static
  static_dir: static
  expiration: '600d'

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /appengine.*
  script: admin_main.app
  login: admin

- url: .*
  script: main.app

builtins:
- admin_redirect: on
- appstats: on
- deferred: on

inbound_services:
- warmup

env_variables:
  DJANGO_SETTINGS_MODULE: 'django_settings'

libraries:
- name: django
  version: "1.4"
- name: webob
  version: "1.1.1"
- name: pycrypto
  version: "latest"
- name: webapp2
  version: "latest"
- name: ssl
  version: "latest"
- name: PIL
  version: "latest"
